# Generated by Django 5.1.1 on 2025-03-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactionapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_model',
            name='transaction_id',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
